name: Release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            host: macos-latest
          - target: x86_64-apple-darwin
            host: macos-latest

          - target: i686-pc-windows-msvc
            host: windows-latest
          - target: x86_64-pc-windows-msvc
            host: windows-latest
          - target: aarch64-pc-windows-msvc
            host: windows-latest

          - target: aarch64-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-aarch64-linux-gnu
          - target: aarch64-unknown-linux-musl
            host: ubuntu-latest
            toolchain: gcc-aarch64-linux-gnu
          - target: aarch64-unknown-linux-ohos
            host: ubuntu-latest
            toolchain: gcc-aarch64-linux-gnu

          - target: i686-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-i686-linux-gnu

          - target: arm-unknown-linux-gnueabi
            host: ubuntu-latest
            toolchain: gcc-arm-linux-gnueabi
          - target: arm-unknown-linux-gnueabihf
            host: ubuntu-latest
            toolchain: gcc-arm-linux-gnueabihf

          # - target: armv7-unknown-linux-gnueabihf
          #   host: ubuntu-latest
          # - target: armv7-unknown-linux-ohos
          #   host: ubuntu-latest

          - target: loongarch64-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-loongarch64-linux-gnu
          - target: loongarch64-unknown-linux-musl
            host: ubuntu-latest
            toolchain: gcc-loongarch64-linux-gnu

          - target: powerpc-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-powerpc-linux-gnu

          - target: powerpc64-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-powerpc64-linux-gnu

          - target: powerpc64le-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: powerpc64le-unknown-linux-gnu
          - target: powerpc64le-unknown-linux-musl
            host: ubuntu-latest
            toolchain: powerpc64le-unknown-linux-gnu

          - target: riscv64gc-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-riscv64-linux-gnu
          - target: riscv64gc-unknown-linux-musl
            host: ubuntu-latest
            toolchain: gcc-riscv64-linux-gnu

          - target: s390x-unknown-linux-gnu
            host: ubuntu-latest
            toolchain: gcc-s390x-linux-gnu

          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
          - target: x86_64-unknown-freebsd
            host: ubuntu-latest
          - target: x86_64-unknown-illumos
            host: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
          - target: x86_64-unknown-linux-ohos
            host: ubuntu-latest
          - target: x86_64-unknown-netbsd
            host: ubuntu-latest
          - target: x86_64-pc-solaris
            host: ubuntu-latest

          - target: sparcv9-sun-solaris
            host: ubuntu-latest
            toolchain: gcc-sparc64-linux-gnu
    runs-on: ${{matrix.host}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Linux dependencies
        if: matrix.host == 'ubuntu-latest'
        run: |
          if [ -n "${{matrix.toolchain}}" ]; then
              sudo apt update
              sudo apt install "${TOOLCHAIN}"
          fi
      - name: Build
        shell: bash
        run: |
          if [ -n "${{matrix.toolchain}}" ]; then
              export CC=${{matrix.toolchain}}
          elif [ -n "$(echo "${{matrix.target}}" | grep x86_64)" ]; then
              export CC=gcc
          fi

          rustup target add ${{matrix.target}}
          cargo build --target ${{matrix.target}} --release --locked
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: neighborhood_cli-${{matrix.target}}
          path: ./target/${{matrix.target}}/release/neighborhood_cli
          if-no-files-found: error
