name: Release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - powerpc64le-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{matrix.target}}
          args: --locked --release
          strip: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: neighborhood_cli-${{matrix.target}}
          path: ./target/${{matrix.target}}/release/neighborhood_cli
          if-no-files-found: error
