name: Release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            host: macos-latest
          - target: x86_64-apple-darwin
            host: macos-latest

          - target: i686-pc-windows-gnu
            host: ubuntu-latest
            packages: gcc-mingw-w64-i686
            toolchain: i686-w64-mingw32-gcc
            executable-suffix: .exe
          - target: x86_64-pc-windows-gnu
            host: ubuntu-latest
            packages: gcc-mingw-w64-x86-64
            toolchain: x86_64-w64-mingw32-gcc
            executable-suffix: .exe
          - target: aarch64-pc-windows-msvc
            host: windows-latest
            executable-suffix: .exe
          # - target: aarch64-pc-windows-gnullvm
          #   host: ubuntu-latest
          #   executable-suffix: .exe

          - target: aarch64-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-aarch64-linux-gnu
            toolchain: aarch64-linux-gnu-gcc
          - target: aarch64-unknown-linux-musl
            host: ubuntu-latest
            packages: gcc-aarch64-linux-gnu
            toolchain: aarch64-linux-gnu-gcc
          # - target: aarch64-unknown-linux-ohos
          #   host: ubuntu-latest
          #   packages: gcc-aarch64-linux-gnu libunwind-dev:arm64
          #   toolchain: aarch64-linux-gnu-gcc

          - target: i686-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-i686-linux-gnu
            toolchain: i686-linux-gnu-gcc

          - target: arm-unknown-linux-gnueabi
            host: ubuntu-latest
            packages: gcc-arm-linux-gnueabi
            toolchain: arm-linux-gnueabi-gcc
          - target: arm-unknown-linux-gnueabihf
            host: ubuntu-latest
            packages: gcc-arm-linux-gnueabihf
            toolchain: arm-linux-gnueabihf-gcc

          # - target: armv7-unknown-linux-gnueabihf
          #   host: ubuntu-latest
          # - target: armv7-unknown-linux-ohos
          #   host: ubuntu-latest

          # TODO: uncomment when ubuntu-latest becomes 25.04
          # - target: loongarch64-unknown-linux-gnu
          #   host: ubuntu-latest
          #   packages: gcc-loongarch64-linux-gnu
          #   toolchain: loongarch64-linux-gnu-gcc
          # - target: loongarch64-unknown-linux-musl
          #   host: ubuntu-latest
          #   packages: gcc-loongarch64-linux-gnu
          #   toolchain: loongarch64-linux-gnu-gcc

          - target: powerpc-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-powerpc-linux-gnu
            toolchain: powerpc-linux-gnu-gcc

          - target: powerpc64-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-powerpc64-linux-gnu
            toolchain: powerpc64-linux-gnu-gcc

          - target: powerpc64le-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-powerpc64le-linux-gnu
            toolchain: powerpc64le-linux-gnu-gcc
          - target: powerpc64le-unknown-linux-musl
            host: ubuntu-latest
            packages: gcc-powerpc64le-linux-gnu
            toolchain: powerpc64le-linux-gnu-gcc

          - target: riscv64gc-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-riscv64-linux-gnu
            toolchain: riscv64-linux-gnu-gcc
          - target: riscv64gc-unknown-linux-musl
            host: ubuntu-latest
            packages: gcc-riscv64-linux-gnu
            toolchain: riscv64-linux-gnu-gcc

          - target: s390x-unknown-linux-gnu
            host: ubuntu-latest
            packages: gcc-s390x-linux-gnu
            toolchain: s390x-linux-gnu-gcc

          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
          # - target: x86_64-unknown-freebsd
          #   host: ubuntu-latest
          # - target: x86_64-unknown-illumos
          #   host: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
          # - target: x86_64-unknown-linux-ohos
          #   host: ubuntu-latest
          # - target: x86_64-unknown-netbsd
          #   host: ubuntu-latest
          # - target: x86_64-pc-solaris
          #   host: ubuntu-latest

          # - target: sparcv9-sun-solaris
          #   host: ubuntu-latest
          #   packages: gcc-sparc64-linux-gnu
          #   toolchain: sparc64-linux-gnu-gcc
    runs-on: ${{matrix.host}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust toolchain
        run: |
          rustup target add ${{matrix.target}}
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Linux dependencies
        if: runner.os == 'Linux'
        run: |
          if [ -n "${{matrix.packages}}" ]; then
              sudo apt update || true
              sudo apt install "${{matrix.packages}}"
          fi
      - name: Build
        shell: bash
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
        run: |
          if [ -n "${{matrix.toolchain}}" ]; then
              export CC=${{matrix.toolchain}}
              export RUSTFLAGS=-Clinker=${{matrix.toolchain}}
          elif [ -n "$(echo "${{matrix.target}}" | grep "$(arch)" | grep linux)" ]; then
              export CC=gcc
              export RUSTFLAGS="${RUSTFLAGS} -Clinker=gcc"
          fi

          cargo build --target ${{matrix.target}} --release --locked --verbose
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: neighborhood_cli-${{matrix.target}}
          path: ./target/${{matrix.target}}/release/neighborhood_cli${{matrix.executable-suffix}}
          if-no-files-found: error
